paths:
  /v1/product/create:
    post:
      summary: Create a new product
      operationId: createProduct
      tags:
        - Products
      security:
        - BearerAuth: [products:write]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../schemas/product.yml#/components/schemas/CreateProductRequest"
      responses:
        "200":
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: "../schemas/product.yml#/components/schemas/ProductResponse"
        "400":
          description: Validation error
          content:
            application/problem+json:
              schema:
                $ref: "../schemas/common.yml#/components/schemas/Problem"
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "../schemas/common.yml#/components/schemas/Problem"
        "403":
          description: Forbidden - insufficient permissions
          content:
            application/problem+json:
              schema:
                $ref: "../schemas/common.yml#/components/schemas/Problem"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "../schemas/common.yml#/components/schemas/Problem"

  /v1/product/update:
    put:
      summary: Update an existing product
      operationId: updateProduct
      tags:
        - Products
      security:
        - BearerAuth: [products:write]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../schemas/product.yml#/components/schemas/UpdateProductRequest"
      responses:
        "200":
          description: Product updated successfully
          content:
            application/json:
              schema:
                $ref: "../schemas/product.yml#/components/schemas/ProductResponse"
        "400":
          description: Validation error
          content:
            application/problem+json:
              schema:
                $ref: "../schemas/common.yml#/components/schemas/Problem"
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "../schemas/common.yml#/components/schemas/Problem"
        "403":
          description: Forbidden - insufficient permissions
          content:
            application/problem+json:
              schema:
                $ref: "../schemas/common.yml#/components/schemas/Problem"
        "404":
          description: Product not found
          content:
            application/problem+json:
              schema:
                $ref: "../schemas/common.yml#/components/schemas/Problem"
        "412":
          description: Version mismatch (optimistic locking)
          content:
            application/problem+json:
              schema:
                $ref: "../schemas/common.yml#/components/schemas/Problem"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "../schemas/common.yml#/components/schemas/Problem"

  /v1/product/get/{id}:
    get:
      summary: Get a product by ID
      operationId: getProductById
      tags:
        - Products
      security:
        - BearerAuth: [products:read]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Product UUID
      responses:
        "200":
          description: Product retrieved successfully
          content:
            application/json:
              schema:
                $ref: "../schemas/product.yml#/components/schemas/ProductResponse"
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "../schemas/common.yml#/components/schemas/Problem"
        "403":
          description: Forbidden - insufficient permissions
          content:
            application/problem+json:
              schema:
                $ref: "../schemas/common.yml#/components/schemas/Problem"
        "404":
          description: Product not found
          content:
            application/problem+json:
              schema:
                $ref: "../schemas/common.yml#/components/schemas/Problem"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "../schemas/common.yml#/components/schemas/Problem"

  /v1/product/list:
    get:
      summary: Get a paginated list of products
      operationId: getProductList
      tags:
        - Products
      security:
        - BearerAuth: [products:read]
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
            minimum: 1
            example: 1
          description: Page number (1-based)
        - name: size
          in: query
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 100
            example: 20
          description: Number of items per page (max 100)
        - name: enabled
          in: query
          required: false
          schema:
            type: boolean
            example: true
          description: Filter by enabled status
        - name: categoryId
          in: query
          required: false
          schema:
            type: string
            format: uuid
            example: "123e4567-e89b-12d3-a456-426614174000"
          description: Filter by category ID
        - name: sort
          in: query
          required: false
          schema:
            type: string
            enum: [name, price, quantity, createdAt, modifiedAt, categoryId]
            example: createdAt
          description: Field to sort by
        - name: order
          in: query
          required: false
          schema:
            type: string
            enum: [asc, desc]
            default: desc
            example: desc
          description: Sort order
      responses:
        "200":
          description: List of products retrieved successfully
          content:
            application/json:
              schema:
                $ref: "../schemas/product.yml#/components/schemas/ProductListResponse"
        "400":
          description: Validation error
          content:
            application/problem+json:
              schema:
                $ref: "../schemas/common.yml#/components/schemas/Problem"
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "../schemas/common.yml#/components/schemas/Problem"
        "403":
          description: Forbidden - insufficient permissions
          content:
            application/problem+json:
              schema:
                $ref: "../schemas/common.yml#/components/schemas/Problem"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "../schemas/common.yml#/components/schemas/Problem"
